remote_theme: pmarsceill/just-the-docs
logo: "/assets/logo-mini.png"

gh_edit_link: true
gh_edit_link_text: Edit this page
gh_edit_repository: https://github.com/bazel-contrib/SIG-rules-authors
gh_edit_branch: gh-pages
gh_edit_view_mode: edit
